### ISSUE TITLE
corruped zip file

### ISSUE THREAD

**Issue by LazyTurtle61** [jimmyjon711/FactorioExtended-Plus-Machines#21]
![20200615142749_1](https://user-images.githubusercontent.com/64089224/84658545-56493100-af16-11ea-9334-ed53aebe702d.jpg)

looks like it has to do with factorio extended plus machines, my friend gets this error when trying to load the game while i have the same versions of all mods and factorio and dont have the problem, got any idea how this happends?

**Comment by LazyTurtle61** [comment]
works on 0.18.30 for him

**Comment by LazyTurtle61** [comment]
![Aantekening 2020-06-16 195811](https://user-images.githubusercontent.com/64089224/84810808-24b29180-b00c-11ea-8a2f-17a0e276cd41.png)
more ppl having the same bug

**Comment by LazyTurtle61** [comment]
testing: FactorioExtended-Plus-Machines_0.4.4/graphics/entity/centrifuge-mk3/centrifuge-A-mk3.png   bad CRC 9633b4ad  (should be a1f04607)

most likely you uploaded a corrupted zip file to the mod portal i got this fix you need to add from a mod maker ^^

**Comment by jimmyjon711** [comment]
This is really weird because when I upload mods I always download from the mod portal in game, and I compared the one that the game downloaded to the one I just downloaded on the mod portal and they don't match.
So I deleted 0.4.4 and reuploaded it, can someone please check to make sure its still not corrupted. I just downloaded it from the mod portal and currently they match.

**Comment by LazyTurtle61** [comment]
Ok thnx m8
