### ISSUE TITLE
Update 17.67 Chemical Plant

### ISSUE THREAD

**Issue by MaxelDel** [jimmyjon711/FactorioExtended-Plus-Machines#6]
In the latest experimental version of factorial the chemical plant was completely reworked
Because of that your mod will always crash

**Comment by xGnoSiSx** [comment]
Confirmed, any way around this until an update is availiable?

**Comment by zerocool444** [comment]
Since the issue is largely visual only, I replaced the `animations` and `working_visualisations` with the original ones from the Factorio update.  Granted I lose the nice graphics, but it at least will load and not crash.

**Comment by zerocool444** [comment]
For those that want to modify their files, in the FactorioExtended-Plus-Machines_0.2.1.zip, extract it, edit the prototypes/entity/entity-assemblers.lua.  It should start around line 537.

Since there is a lot of code to paste, I have attached my file.
[entity-assemblers.zip](https://github.com/jimmyjon711/FactorioExtended-Plus-Machines/files/3572336/entity-assemblers.zip)

**Comment by jimmyjon711** [comment]
Thanks for reporting, I will fix this issue this weekend. Currently I don't have time to fix it now.
